application:
  version: 0.1
spring:
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/equipment
    username: temp_user
    password: temp_pas
    driver-class-name: org.postgresql.Driver
  shell:
    interactive:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update