application:
  version: 0.1
spring:
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/equipment
    username: temp_user
    password: temp_pas
    driver-class-name: org.postgresql.Driver
  shell:
    interactive:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
#  security:
#    enabled: false
#liquibase.change-log=classpath:db/liquibase-changelog.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  server:
    port: 8090
logging:
  file: app.log
  level:
    liquibase: INFO
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    java:
      version: @java.version@