application:
  version: 0.1
spring:
  profiles:
    active: development

---

spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://188.227.18.141:5432/equipment
    username: temp_user
    password: temp_pas
    driver-class-name: org.postgresql.Driver
  shell:
    interactive:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
#liquibase:
#  changeLog: "classpath:/db/changelog/db.changelog-production.yaml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  server:
    port: 8090
logging:
  file: app.log
  level:
    liquibase: INFO
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    java:
      version: @java.version@

---

spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  #    url: jdbc:postgresql://188.227.18.141:5432/equipment
#    username: temp_user
#    password: temp_pas
#    driver-class-name: org.postgresql.Driver
  shell:
    interactive:
      enabled: true
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
